import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [tail, setTail] = useState("");
  const [url, setUrl] = useState("");

  const SetUrl = (name) => {
    document.location.replace(document.location.origin + "/" + name);
  };
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>
        <div className={styles.box}>
          <div className={styles.inner}>
            <input
              className={styles.input}
              type="text"
              placeholder="enter tail"
              value={tail}
              onChange={(e) => setTail(e.target.value)}
            />
            <button
              className={styles.button}
              onClick={() => tail && SetUrl(tail)}
            >
              Search
            </button>
          </div>
          <div className={styles.inner}>
            <input
              className={styles.input}
              type="text"
              placeholder="enter tail"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
            />
            <button
              className={styles.button}
              onClick={() => localStorage.setItem("url", url)}
            >
              Add json
            </button>
            <button
              className={styles.button}
              onClick={() => localStorage.clear("url")}
            >
              Clear json
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
